"""initial migration

Revision ID: 2b2629551cb1
Revises: 
Create Date: 2019-07-27 12:11:42.734595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2629551cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'down_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('down_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
