"""initial migration

Revision ID: 98ed15ec2a0b
Revises: 2b2629551cb1
Create Date: 2019-07-27 15:01:39.142165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ed15ec2a0b'
down_revision = '2b2629551cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('down_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'down_url')
    # ### end Alembic commands ###
