"""initial migration

Revision ID: a18391d3f5a2
Revises: 98ed15ec2a0b
Create Date: 2019-07-27 17:48:30.469898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18391d3f5a2'
down_revision = '98ed15ec2a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('upload', sa.String(length=256), nullable=True))
    op.drop_column('post', 'cover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cover', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('post', 'upload')
    # ### end Alembic commands ###
